INFO     celery.worker.consumer.connection:connection.py:22 Connected to memory://localhost//
INFO     celery.app.trace:trace.py:128 Task celery.ping[82ea2321-5d64-48fd-915b-d8d121907d7f] succeeded in 0.032304213999992726s: 'pong'
INFO     httpx:_client.py:1025 HTTP Request: POST http://testserver/api/words "HTTP/1.1 303 See Other"
INFO     root:client.py:77 ->> POST /api/words
INFO     root:client.py:83 Query params: None
INFO     root:client.py:86 Request body: None
INFO     root:client.py:88 <<- 303
INFO     root:client.py:91 None
INFO     httpx:_client.py:1025 HTTP Request: GET http://testserver/api/words/1652d14d-b208-447b-ae06-5980834e5c0f "HTTP/1.1 202 Accepted"
INFO     root:client.py:77 ->> GET /api/words/1652d14d-b208-447b-ae06-5980834e5c0f
INFO     root:client.py:83 Query params: None
INFO     root:client.py:88 <<- 202
INFO     root:client.py:94 
INFO     httpx:_client.py:1025 HTTP Request: GET http://testserver/api/words/1652d14d-b208-447b-ae06-5980834e5c0f "HTTP/1.1 202 Accepted"
INFO     root:client.py:77 ->> GET /api/words/1652d14d-b208-447b-ae06-5980834e5c0f
INFO     root:client.py:83 Query params: None
INFO     root:client.py:88 <<- 202
INFO     root:client.py:94 
INFO     celery.worker.strategy:strategy.py:161 Task tasks.words[1652d14d-b208-447b-ae06-5980834e5c0f] received
INFO     celery.app.trace:trace.py:128 Task tasks.words[1652d14d-b208-447b-ae06-5980834e5c0f] succeeded in 0.018879569999995738s: 69
INFO     httpx:_client.py:1025 HTTP Request: GET http://testserver/api/words/1652d14d-b208-447b-ae06-5980834e5c0f "HTTP/1.1 200 OK"
INFO     root:client.py:77 ->> GET /api/words/1652d14d-b208-447b-ae06-5980834e5c0f
INFO     root:client.py:83 Query params: None
INFO     root:client.py:88 <<- 200
INFO     root:client.py:91 {'count': 69}