INFO     celery.worker.consumer.connection:connection.py:22 Connected to memory://localhost//
INFO     celery.app.trace:trace.py:128 Task celery.ping[ba9c40e3-0767-4aed-91e4-05d23eb513d9] succeeded in 0.04727652299999363s: 'pong'
INFO     httpx:_client.py:1025 HTTP Request: POST http://testserver/api/words "HTTP/1.1 303 See Other"
INFO     root:client.py:77 ->> POST /api/words
INFO     root:client.py:83 Query params: None
INFO     root:client.py:86 Request body: None
INFO     root:client.py:88 <<- 303
INFO     root:client.py:91 None
INFO     httpx:_client.py:1025 HTTP Request: GET http://testserver/api/words/09f23bf3-51b6-4ac1-8664-7fdf80fabb29 "HTTP/1.1 202 Accepted"
INFO     root:client.py:77 ->> GET /api/words/09f23bf3-51b6-4ac1-8664-7fdf80fabb29
INFO     root:client.py:83 Query params: None
INFO     root:client.py:88 <<- 202
INFO     root:client.py:94 
INFO     httpx:_client.py:1025 HTTP Request: GET http://testserver/api/words/09f23bf3-51b6-4ac1-8664-7fdf80fabb29 "HTTP/1.1 202 Accepted"
INFO     root:client.py:77 ->> GET /api/words/09f23bf3-51b6-4ac1-8664-7fdf80fabb29
INFO     root:client.py:83 Query params: None
INFO     root:client.py:88 <<- 202
INFO     root:client.py:94 
INFO     celery.worker.strategy:strategy.py:161 Task tasks.words[09f23bf3-51b6-4ac1-8664-7fdf80fabb29] received
INFO     celery.app.trace:trace.py:128 Task tasks.words[09f23bf3-51b6-4ac1-8664-7fdf80fabb29] succeeded in 0.02083318600000439s: 69
INFO     httpx:_client.py:1025 HTTP Request: GET http://testserver/api/words/09f23bf3-51b6-4ac1-8664-7fdf80fabb29 "HTTP/1.1 200 OK"
INFO     root:client.py:77 ->> GET /api/words/09f23bf3-51b6-4ac1-8664-7fdf80fabb29
INFO     root:client.py:83 Query params: None
INFO     root:client.py:88 <<- 200
INFO     root:client.py:91 {'count': 69}