INFO     celery.worker.consumer.connection:connection.py:22 Connected to memory://localhost//
INFO     celery.app.trace:trace.py:128 Task celery.ping[d8c873a4-bf20-4c24-bf9a-100f5f5d4e66] succeeded in 0.03213835099998619s: 'pong'
INFO     httpx:_client.py:1026 HTTP Request: POST http://testserver/api/words "HTTP/1.1 303 See Other"
INFO     root:client.py:77 ->> POST /api/words
INFO     root:client.py:83 Query params: None
INFO     root:client.py:86 Request body: None
INFO     root:client.py:88 <<- 303
INFO     root:client.py:91 None
INFO     httpx:_client.py:1026 HTTP Request: GET http://testserver/api/words/6c1eb065-ac9c-4886-86ec-c530fc6c7bf9 "HTTP/1.1 202 Accepted"
INFO     root:client.py:77 ->> GET /api/words/6c1eb065-ac9c-4886-86ec-c530fc6c7bf9
INFO     root:client.py:83 Query params: None
INFO     root:client.py:88 <<- 202
INFO     root:client.py:94 
INFO     httpx:_client.py:1026 HTTP Request: GET http://testserver/api/words/6c1eb065-ac9c-4886-86ec-c530fc6c7bf9 "HTTP/1.1 202 Accepted"
INFO     root:client.py:77 ->> GET /api/words/6c1eb065-ac9c-4886-86ec-c530fc6c7bf9
INFO     root:client.py:83 Query params: None
INFO     root:client.py:88 <<- 202
INFO     root:client.py:94 
INFO     celery.worker.strategy:strategy.py:161 Task tasks.words[6c1eb065-ac9c-4886-86ec-c530fc6c7bf9] received
INFO     celery.app.trace:trace.py:128 Task tasks.words[6c1eb065-ac9c-4886-86ec-c530fc6c7bf9] succeeded in 0.013156039000023156s: 69
INFO     httpx:_client.py:1026 HTTP Request: GET http://testserver/api/words/6c1eb065-ac9c-4886-86ec-c530fc6c7bf9 "HTTP/1.1 200 OK"
INFO     root:client.py:77 ->> GET /api/words/6c1eb065-ac9c-4886-86ec-c530fc6c7bf9
INFO     root:client.py:83 Query params: None
INFO     root:client.py:88 <<- 200
INFO     root:client.py:91 {'count': 69}