INFO     celery.worker.consumer.connection:connection.py:22 Connected to memory://localhost//
INFO     celery.app.trace:trace.py:128 Task celery.ping[84f9dfc8-093f-4b87-a046-efaed16add4e] succeeded in 0.032780439999982036s: 'pong'
INFO     httpx:_client.py:1026 HTTP Request: POST http://testserver/api/words "HTTP/1.1 303 See Other"
INFO     root:client.py:77 ->> POST /api/words
INFO     root:client.py:83 Query params: None
INFO     root:client.py:86 Request body: None
INFO     root:client.py:88 <<- 303
INFO     root:client.py:91 None
INFO     httpx:_client.py:1026 HTTP Request: GET http://testserver/api/words/4b8eae0d-1e12-4969-a83a-d0b7a338b9a8 "HTTP/1.1 202 Accepted"
INFO     root:client.py:77 ->> GET /api/words/4b8eae0d-1e12-4969-a83a-d0b7a338b9a8
INFO     root:client.py:83 Query params: None
INFO     root:client.py:88 <<- 202
INFO     root:client.py:94 
INFO     httpx:_client.py:1026 HTTP Request: GET http://testserver/api/words/4b8eae0d-1e12-4969-a83a-d0b7a338b9a8 "HTTP/1.1 202 Accepted"
INFO     root:client.py:77 ->> GET /api/words/4b8eae0d-1e12-4969-a83a-d0b7a338b9a8
INFO     root:client.py:83 Query params: None
INFO     root:client.py:88 <<- 202
INFO     root:client.py:94 
INFO     celery.worker.strategy:strategy.py:161 Task tasks.words[4b8eae0d-1e12-4969-a83a-d0b7a338b9a8] received
INFO     celery.app.trace:trace.py:128 Task tasks.words[4b8eae0d-1e12-4969-a83a-d0b7a338b9a8] succeeded in 0.021964483000004975s: 69
INFO     httpx:_client.py:1026 HTTP Request: GET http://testserver/api/words/4b8eae0d-1e12-4969-a83a-d0b7a338b9a8 "HTTP/1.1 200 OK"
INFO     root:client.py:77 ->> GET /api/words/4b8eae0d-1e12-4969-a83a-d0b7a338b9a8
INFO     root:client.py:83 Query params: None
INFO     root:client.py:88 <<- 200
INFO     root:client.py:91 {'count': 69}