INFO     celery.worker.consumer.connection:connection.py:22 Connected to memory://localhost//
INFO     celery.app.trace:trace.py:128 Task celery.ping[b7f71659-df42-4ba8-95c9-1818d0cd5fb2] succeeded in 0.03273223200000075s: 'pong'
INFO     httpx:_client.py:1026 HTTP Request: POST http://testserver/api/words "HTTP/1.1 303 See Other"
INFO     root:client.py:77 ->> POST /api/words
INFO     root:client.py:83 Query params: None
INFO     root:client.py:86 Request body: None
INFO     root:client.py:88 <<- 303
INFO     root:client.py:91 None
INFO     httpx:_client.py:1026 HTTP Request: GET http://testserver/api/words/3295fc77-76f4-4733-8626-93acc12cbd18 "HTTP/1.1 202 Accepted"
INFO     root:client.py:77 ->> GET /api/words/3295fc77-76f4-4733-8626-93acc12cbd18
INFO     root:client.py:83 Query params: None
INFO     root:client.py:88 <<- 202
INFO     root:client.py:94 
INFO     httpx:_client.py:1026 HTTP Request: GET http://testserver/api/words/3295fc77-76f4-4733-8626-93acc12cbd18 "HTTP/1.1 202 Accepted"
INFO     root:client.py:77 ->> GET /api/words/3295fc77-76f4-4733-8626-93acc12cbd18
INFO     root:client.py:83 Query params: None
INFO     root:client.py:88 <<- 202
INFO     root:client.py:94 
INFO     celery.worker.strategy:strategy.py:161 Task tasks.words[3295fc77-76f4-4733-8626-93acc12cbd18] received
INFO     celery.app.trace:trace.py:128 Task tasks.words[3295fc77-76f4-4733-8626-93acc12cbd18] succeeded in 0.02201868099996318s: 69
INFO     httpx:_client.py:1026 HTTP Request: GET http://testserver/api/words/3295fc77-76f4-4733-8626-93acc12cbd18 "HTTP/1.1 200 OK"
INFO     root:client.py:77 ->> GET /api/words/3295fc77-76f4-4733-8626-93acc12cbd18
INFO     root:client.py:83 Query params: None
INFO     root:client.py:88 <<- 200
INFO     root:client.py:91 {'count': 69}