INFO     celery.worker.consumer.connection:connection.py:22 Connected to memory://localhost//
INFO     celery.app.trace:trace.py:128 Task celery.ping[60a94235-9df0-43f6-b48f-705b2de9cc77] succeeded in 0.04669855099999154s: 'pong'
INFO     httpx:_client.py:1025 HTTP Request: POST http://testserver/api/words "HTTP/1.1 303 See Other"
INFO     root:client.py:77 ->> POST /api/words
INFO     root:client.py:83 Query params: None
INFO     root:client.py:86 Request body: None
INFO     root:client.py:88 <<- 303
INFO     root:client.py:91 None
INFO     httpx:_client.py:1025 HTTP Request: GET http://testserver/api/words/40b7e2c6-190e-4fd9-b1eb-bb3b0bf06d0c "HTTP/1.1 202 Accepted"
INFO     root:client.py:77 ->> GET /api/words/40b7e2c6-190e-4fd9-b1eb-bb3b0bf06d0c
INFO     root:client.py:83 Query params: None
INFO     root:client.py:88 <<- 202
INFO     root:client.py:94 
INFO     httpx:_client.py:1025 HTTP Request: GET http://testserver/api/words/40b7e2c6-190e-4fd9-b1eb-bb3b0bf06d0c "HTTP/1.1 202 Accepted"
INFO     root:client.py:77 ->> GET /api/words/40b7e2c6-190e-4fd9-b1eb-bb3b0bf06d0c
INFO     root:client.py:83 Query params: None
INFO     root:client.py:88 <<- 202
INFO     root:client.py:94 
INFO     celery.worker.strategy:strategy.py:161 Task tasks.words[40b7e2c6-190e-4fd9-b1eb-bb3b0bf06d0c] received
INFO     celery.app.trace:trace.py:128 Task tasks.words[40b7e2c6-190e-4fd9-b1eb-bb3b0bf06d0c] succeeded in 0.028056010000000242s: 69
INFO     httpx:_client.py:1025 HTTP Request: GET http://testserver/api/words/40b7e2c6-190e-4fd9-b1eb-bb3b0bf06d0c "HTTP/1.1 200 OK"
INFO     root:client.py:77 ->> GET /api/words/40b7e2c6-190e-4fd9-b1eb-bb3b0bf06d0c
INFO     root:client.py:83 Query params: None
INFO     root:client.py:88 <<- 200
INFO     root:client.py:91 {'count': 69}