INFO     celery.worker.consumer.connection:connection.py:22 Connected to memory://localhost//
INFO     celery.app.trace:trace.py:128 Task celery.ping[868f8d28-65fe-4182-8e4d-642ece2aeb52] succeeded in 0.03217401200004133s: 'pong'
INFO     httpx:_client.py:1025 HTTP Request: POST http://testserver/api/words "HTTP/1.1 303 See Other"
INFO     root:client.py:77 ->> POST /api/words
INFO     root:client.py:83 Query params: None
INFO     root:client.py:86 Request body: None
INFO     root:client.py:88 <<- 303
INFO     root:client.py:91 None
INFO     httpx:_client.py:1025 HTTP Request: GET http://testserver/api/words/50df37c5-57c5-4adc-aab9-48fb36f22347 "HTTP/1.1 202 Accepted"
INFO     root:client.py:77 ->> GET /api/words/50df37c5-57c5-4adc-aab9-48fb36f22347
INFO     root:client.py:83 Query params: None
INFO     root:client.py:88 <<- 202
INFO     root:client.py:94 
INFO     httpx:_client.py:1025 HTTP Request: GET http://testserver/api/words/50df37c5-57c5-4adc-aab9-48fb36f22347 "HTTP/1.1 202 Accepted"
INFO     root:client.py:77 ->> GET /api/words/50df37c5-57c5-4adc-aab9-48fb36f22347
INFO     root:client.py:83 Query params: None
INFO     root:client.py:88 <<- 202
INFO     root:client.py:94 
INFO     celery.worker.strategy:strategy.py:161 Task tasks.words[50df37c5-57c5-4adc-aab9-48fb36f22347] received
INFO     celery.app.trace:trace.py:128 Task tasks.words[50df37c5-57c5-4adc-aab9-48fb36f22347] succeeded in 0.012990387000002102s: 69
INFO     httpx:_client.py:1025 HTTP Request: GET http://testserver/api/words/50df37c5-57c5-4adc-aab9-48fb36f22347 "HTTP/1.1 200 OK"
INFO     root:client.py:77 ->> GET /api/words/50df37c5-57c5-4adc-aab9-48fb36f22347
INFO     root:client.py:83 Query params: None
INFO     root:client.py:88 <<- 200
INFO     root:client.py:91 {'count': 69}