INFO     celery.worker.consumer.connection:connection.py:22 Connected to memory://localhost//
INFO     celery.app.trace:trace.py:128 Task celery.ping[eea87dbe-dee7-4906-95fb-2b8a0d8dbc5a] succeeded in 0.04499671500002478s: 'pong'
INFO     httpx:_client.py:1025 HTTP Request: POST http://testserver/api/words "HTTP/1.1 303 See Other"
INFO     root:client.py:77 ->> POST /api/words
INFO     root:client.py:83 Query params: None
INFO     root:client.py:86 Request body: None
INFO     root:client.py:88 <<- 303
INFO     root:client.py:91 None
INFO     httpx:_client.py:1025 HTTP Request: GET http://testserver/api/words/80465c8e-6d5c-4379-bca6-544800cec476 "HTTP/1.1 202 Accepted"
INFO     root:client.py:77 ->> GET /api/words/80465c8e-6d5c-4379-bca6-544800cec476
INFO     root:client.py:83 Query params: None
INFO     root:client.py:88 <<- 202
INFO     root:client.py:94 
INFO     httpx:_client.py:1025 HTTP Request: GET http://testserver/api/words/80465c8e-6d5c-4379-bca6-544800cec476 "HTTP/1.1 202 Accepted"
INFO     root:client.py:77 ->> GET /api/words/80465c8e-6d5c-4379-bca6-544800cec476
INFO     root:client.py:83 Query params: None
INFO     root:client.py:88 <<- 202
INFO     root:client.py:94 
INFO     celery.worker.strategy:strategy.py:161 Task tasks.words[80465c8e-6d5c-4379-bca6-544800cec476] received
INFO     celery.app.trace:trace.py:128 Task tasks.words[80465c8e-6d5c-4379-bca6-544800cec476] succeeded in 0.028045794000007618s: 69
INFO     httpx:_client.py:1025 HTTP Request: GET http://testserver/api/words/80465c8e-6d5c-4379-bca6-544800cec476 "HTTP/1.1 200 OK"
INFO     root:client.py:77 ->> GET /api/words/80465c8e-6d5c-4379-bca6-544800cec476
INFO     root:client.py:83 Query params: None
INFO     root:client.py:88 <<- 200
INFO     root:client.py:91 {'count': 69}