INFO     celery.worker.consumer.connection:connection.py:22 Connected to memory://localhost//
INFO     celery.app.trace:trace.py:128 Task celery.ping[780eef03-6c36-4fcf-835c-5b2aafafab00] succeeded in 0.048309933999973964s: 'pong'
INFO     httpx:_client.py:1025 HTTP Request: POST http://testserver/api/words "HTTP/1.1 303 See Other"
INFO     root:client.py:77 ->> POST /api/words
INFO     root:client.py:83 Query params: None
INFO     root:client.py:86 Request body: None
INFO     root:client.py:88 <<- 303
INFO     root:client.py:91 None
INFO     httpx:_client.py:1025 HTTP Request: GET http://testserver/api/words/2608678f-27cb-401a-ba44-3d50730d7c0f "HTTP/1.1 202 Accepted"
INFO     root:client.py:77 ->> GET /api/words/2608678f-27cb-401a-ba44-3d50730d7c0f
INFO     root:client.py:83 Query params: None
INFO     root:client.py:88 <<- 202
INFO     root:client.py:94 
INFO     httpx:_client.py:1025 HTTP Request: GET http://testserver/api/words/2608678f-27cb-401a-ba44-3d50730d7c0f "HTTP/1.1 202 Accepted"
INFO     root:client.py:77 ->> GET /api/words/2608678f-27cb-401a-ba44-3d50730d7c0f
INFO     root:client.py:83 Query params: None
INFO     root:client.py:88 <<- 202
INFO     root:client.py:94 
INFO     celery.worker.strategy:strategy.py:161 Task tasks.words[2608678f-27cb-401a-ba44-3d50730d7c0f] received
INFO     celery.app.trace:trace.py:128 Task tasks.words[2608678f-27cb-401a-ba44-3d50730d7c0f] succeeded in 0.024662765000016407s: 69
INFO     httpx:_client.py:1025 HTTP Request: GET http://testserver/api/words/2608678f-27cb-401a-ba44-3d50730d7c0f "HTTP/1.1 200 OK"
INFO     root:client.py:77 ->> GET /api/words/2608678f-27cb-401a-ba44-3d50730d7c0f
INFO     root:client.py:83 Query params: None
INFO     root:client.py:88 <<- 200
INFO     root:client.py:91 {'count': 69}