INFO     celery.worker.consumer.connection:connection.py:22 Connected to memory://localhost//
INFO     celery.app.trace:trace.py:128 Task celery.ping[f1a2cd6b-a77a-42d4-a098-69d8396ba21a] succeeded in 0.03010838400001603s: 'pong'
INFO     httpx:_client.py:1025 HTTP Request: POST http://testserver/api/words "HTTP/1.1 303 See Other"
INFO     root:client.py:77 ->> POST /api/words
INFO     root:client.py:83 Query params: None
INFO     root:client.py:86 Request body: None
INFO     root:client.py:88 <<- 303
INFO     root:client.py:91 None
INFO     httpx:_client.py:1025 HTTP Request: GET http://testserver/api/words/4e6dde27-f78b-470c-ae18-a3aface00e77 "HTTP/1.1 202 Accepted"
INFO     root:client.py:77 ->> GET /api/words/4e6dde27-f78b-470c-ae18-a3aface00e77
INFO     root:client.py:83 Query params: None
INFO     root:client.py:88 <<- 202
INFO     root:client.py:94 
INFO     httpx:_client.py:1025 HTTP Request: GET http://testserver/api/words/4e6dde27-f78b-470c-ae18-a3aface00e77 "HTTP/1.1 202 Accepted"
INFO     root:client.py:77 ->> GET /api/words/4e6dde27-f78b-470c-ae18-a3aface00e77
INFO     root:client.py:83 Query params: None
INFO     root:client.py:88 <<- 202
INFO     root:client.py:94 
INFO     celery.worker.strategy:strategy.py:161 Task tasks.words[4e6dde27-f78b-470c-ae18-a3aface00e77] received
INFO     celery.app.trace:trace.py:128 Task tasks.words[4e6dde27-f78b-470c-ae18-a3aface00e77] succeeded in 0.011104334000037852s: 69
INFO     httpx:_client.py:1025 HTTP Request: GET http://testserver/api/words/4e6dde27-f78b-470c-ae18-a3aface00e77 "HTTP/1.1 200 OK"
INFO     root:client.py:77 ->> GET /api/words/4e6dde27-f78b-470c-ae18-a3aface00e77
INFO     root:client.py:83 Query params: None
INFO     root:client.py:88 <<- 200
INFO     root:client.py:91 {'count': 69}