INFO     celery.worker.consumer.connection:connection.py:22 Connected to memory://localhost//
INFO     celery.app.trace:trace.py:128 Task celery.ping[a027f272-26c9-469e-bbe3-f357da84f9dc] succeeded in 0.04880500699999857s: 'pong'
INFO     httpx:_client.py:1025 HTTP Request: POST http://testserver/api/words "HTTP/1.1 303 See Other"
INFO     root:client.py:77 ->> POST /api/words
INFO     root:client.py:83 Query params: None
INFO     root:client.py:86 Request body: None
INFO     root:client.py:88 <<- 303
INFO     root:client.py:91 None
INFO     httpx:_client.py:1025 HTTP Request: GET http://testserver/api/words/d33c9dfa-b583-480a-ac96-69ed7ad800b4 "HTTP/1.1 202 Accepted"
INFO     root:client.py:77 ->> GET /api/words/d33c9dfa-b583-480a-ac96-69ed7ad800b4
INFO     root:client.py:83 Query params: None
INFO     root:client.py:88 <<- 202
INFO     root:client.py:94 
INFO     httpx:_client.py:1025 HTTP Request: GET http://testserver/api/words/d33c9dfa-b583-480a-ac96-69ed7ad800b4 "HTTP/1.1 202 Accepted"
INFO     root:client.py:77 ->> GET /api/words/d33c9dfa-b583-480a-ac96-69ed7ad800b4
INFO     root:client.py:83 Query params: None
INFO     root:client.py:88 <<- 202
INFO     root:client.py:94 
INFO     celery.worker.strategy:strategy.py:161 Task tasks.words[d33c9dfa-b583-480a-ac96-69ed7ad800b4] received
INFO     celery.app.trace:trace.py:128 Task tasks.words[d33c9dfa-b583-480a-ac96-69ed7ad800b4] succeeded in 0.022536631000008356s: 69
INFO     httpx:_client.py:1025 HTTP Request: GET http://testserver/api/words/d33c9dfa-b583-480a-ac96-69ed7ad800b4 "HTTP/1.1 200 OK"
INFO     root:client.py:77 ->> GET /api/words/d33c9dfa-b583-480a-ac96-69ed7ad800b4
INFO     root:client.py:83 Query params: None
INFO     root:client.py:88 <<- 200
INFO     root:client.py:91 {'count': 69}