INFO     celery.worker.consumer.connection:connection.py:22 Connected to memory://localhost//
INFO     celery.app.trace:trace.py:128 Task celery.ping[e8cc967f-852f-4ffb-a1e1-056ae2d6c639] succeeded in 0.04986416200000576s: 'pong'
INFO     httpx:_client.py:1025 HTTP Request: POST http://testserver/api/words "HTTP/1.1 303 See Other"
INFO     root:client.py:77 ->> POST /api/words
INFO     root:client.py:83 Query params: None
INFO     root:client.py:86 Request body: None
INFO     root:client.py:88 <<- 303
INFO     root:client.py:91 None
INFO     httpx:_client.py:1025 HTTP Request: GET http://testserver/api/words/3851afed-8b33-47ea-ad28-6da95736dd0a "HTTP/1.1 202 Accepted"
INFO     root:client.py:77 ->> GET /api/words/3851afed-8b33-47ea-ad28-6da95736dd0a
INFO     root:client.py:83 Query params: None
INFO     root:client.py:88 <<- 202
INFO     root:client.py:94 
INFO     httpx:_client.py:1025 HTTP Request: GET http://testserver/api/words/3851afed-8b33-47ea-ad28-6da95736dd0a "HTTP/1.1 202 Accepted"
INFO     root:client.py:77 ->> GET /api/words/3851afed-8b33-47ea-ad28-6da95736dd0a
INFO     root:client.py:83 Query params: None
INFO     root:client.py:88 <<- 202
INFO     root:client.py:94 
INFO     celery.worker.strategy:strategy.py:161 Task tasks.words[3851afed-8b33-47ea-ad28-6da95736dd0a] received
INFO     celery.app.trace:trace.py:128 Task tasks.words[3851afed-8b33-47ea-ad28-6da95736dd0a] succeeded in 0.02145329600000423s: 69
INFO     httpx:_client.py:1025 HTTP Request: GET http://testserver/api/words/3851afed-8b33-47ea-ad28-6da95736dd0a "HTTP/1.1 200 OK"
INFO     root:client.py:77 ->> GET /api/words/3851afed-8b33-47ea-ad28-6da95736dd0a
INFO     root:client.py:83 Query params: None
INFO     root:client.py:88 <<- 200
INFO     root:client.py:91 {'count': 69}