INFO     celery.worker.consumer.connection:connection.py:22 Connected to memory://localhost//
INFO     celery.app.trace:trace.py:128 Task celery.ping[d76e48fc-afd8-4ad2-aa28-897f53b7356c] succeeded in 0.05727659100000437s: 'pong'
INFO     httpx:_client.py:1025 HTTP Request: POST http://testserver/api/words "HTTP/1.1 303 See Other"
INFO     root:client.py:77 ->> POST /api/words
INFO     root:client.py:83 Query params: None
INFO     root:client.py:86 Request body: None
INFO     root:client.py:88 <<- 303
INFO     root:client.py:91 None
INFO     httpx:_client.py:1025 HTTP Request: GET http://testserver/api/words/fa3df8c6-6d52-4b2d-b452-1ae5349e817a "HTTP/1.1 202 Accepted"
INFO     root:client.py:77 ->> GET /api/words/fa3df8c6-6d52-4b2d-b452-1ae5349e817a
INFO     root:client.py:83 Query params: None
INFO     root:client.py:88 <<- 202
INFO     root:client.py:94 
INFO     httpx:_client.py:1025 HTTP Request: GET http://testserver/api/words/fa3df8c6-6d52-4b2d-b452-1ae5349e817a "HTTP/1.1 202 Accepted"
INFO     root:client.py:77 ->> GET /api/words/fa3df8c6-6d52-4b2d-b452-1ae5349e817a
INFO     root:client.py:83 Query params: None
INFO     root:client.py:88 <<- 202
INFO     root:client.py:94 
INFO     celery.worker.strategy:strategy.py:161 Task tasks.words[fa3df8c6-6d52-4b2d-b452-1ae5349e817a] received
INFO     celery.app.trace:trace.py:128 Task tasks.words[fa3df8c6-6d52-4b2d-b452-1ae5349e817a] succeeded in 0.02020824400000265s: 69
INFO     httpx:_client.py:1025 HTTP Request: GET http://testserver/api/words/fa3df8c6-6d52-4b2d-b452-1ae5349e817a "HTTP/1.1 200 OK"
INFO     root:client.py:77 ->> GET /api/words/fa3df8c6-6d52-4b2d-b452-1ae5349e817a
INFO     root:client.py:83 Query params: None
INFO     root:client.py:88 <<- 200
INFO     root:client.py:91 {'count': 69}